(source melpa)

(depends-on "pallet")

(source gnu)
(depends-on "cask")
(depends-on "dash")
(depends-on "epl")
(depends-on "f")
(depends-on "package-build")
(depends-on "pallet")
(depends-on "s")
(depends-on "shut-up")
