#!/bin/bash

bspc config border_width        1
bspc config window_gap          2

i=1
for monitor in $(bspc query -M); do
bspc monitor $monitor \
	-n "$i" \
	-d $i/{i,ii,iii,iv,v,vi,vii,viii,ix,x}
    let i++
done
NMON=$i
unset i

bspc config bottom_padding 30
bspc config top_padding 10
bspc config left_padding 10
bspc config right_padding 10

# Visual options
bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_follows_pointer true
bspc config auto_alternate true
bspc config auto_cancel true
bspc config normal_border_color "#332d29"
bspc config active_border_color "#817267"
bspc config focused_border_color "#504339"
bspc config presel_border_color "#9a875f"
bspc config urgent_border_color "#9f7155"
bspc config focused_locked_border_color "#9a875f"
bspc config normal_frame_opacity 0.0
bspc config focused_frame_opacity 0.1


# Rules
bspc rule -a Skype pseudo_tiled=on
bspc rule -a Spotify pseudo_tiled=on
bspc rule -a Spacefm pseudo_tiled=on
bspc rule -a Skype pseudo_tiled=on
bspc rule -a File-roller pseudo_tiled=on
bspc rule -a Transmission-gtk pseudo_tiled=on
bspc rule -a Conky sticky=on manage=off lower=on
bspc rule -a astime sticky=on
bspc rule -a Tint2 sticky=on manage=off lower=on
#bspc rule -a feh floating=on manage=on


#open Funny Java Things
bspc config focus_follows_pointer false &
wmname LG3D &
export _JAVA_OPTIONS="-Dawt.useSystemAAFontSettings=on -Dswing.aatext=true -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel" &
xsetroot -cursor_name left_ptr &
xautolock -time 5 -locker slock &
xfce4-power-manager &
xfsettingsd &
thunar-volman &
#wicd-gtk --tray &
start-pulseaudio-x11 &
xfce4-clipman &
compton &
feh --randomize --bg-scale .wallpapers/ &
setxkbmap us &
/usr/bin/sxhkd &
notify-listener &
# /SCRIPT LOAD notify.pl
# devmon-init &
emacs --daemon &
tint2 &
